---
name: "MyAnimeSync"
guid: "28612bb6-e3ab-4099-a682-f413d4ca19d3"
imageUrl: "https://raw.githubusercontent.com/iankiller77/MyAnimeSync/refs/heads/main/jellyfin-plugin-myanimesync.png"
version: "1.6.1.0"
targetAbi: "10.11.11.0"
framework: "net9.0"
overview: "Synchronise watch status on myanimelist."
description: >
  This is a longer description that can span more than one line and include details about your plugin.
category: "General"
owner: "iankiller77"
artifacts:
  - "Jellyfin.Plugin.MyAnimeSync.dll"
changelog: |-
  ### :tada: New features and improvements
  - feature/copy api url on click (#51) @iankiller77
  ### :bug: Bug Fixes
  - bug/wrong_edit_window_location_on_jellyfin_app (#53) @iankiller77
  - bug/label_first_button_function_bleeding_into_the_label (#52) @iankiller77
  - bug/fix_search_regression_with_unidentified_season_number (#50) @iankiller77
