---
name: "MyAnimeSync"
guid: "28612bb6-e3ab-4099-a682-f413d4ca19d3"
imageUrl: "https://raw.githubusercontent.com/iankiller77/MyAnimeSync/refs/heads/main/jellyfin-plugin-myanimesync.png"
version: "1.6.2.0"
targetAbi: "10.11.11.0"
framework: "net9.0"
overview: "Synchronise watch status on myanimelist."
description: >
  This is a longer description that can span more than one line and include details about your plugin.

category: "General"
owner: "iankiller77"
artifacts:
  - "Jellyfin.Plugin.MyAnimeSync.dll"
changelog: |-
  ### :tada: New features and improvements
  - Refactor/improve_code_coverage (#60) @iankiller77
  - feature/consider_serie_production_year_and_type_for_search (#57) @iankiller77
  - refactor/streamlined_update_entry_generation_and_use_for_episode (#56) @iankiller77
  - feature/image_for_plugin_page (#55) @iankiller77
  ### :bug: Bug Fixes
  - bugfix/episode_mismatch_on_ONA_in_between_seasons (#62) @iankiller77
  - bugfix/fix_special_episode_issue_introduced_in_#56 (#59) @iankiller77
